DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS recurring;

CREATE TABLE income (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date TEXT NOT NULL,
	amount REAL NOT NULL,
	category TEXT
);

CREATE TABLE expense (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	date TEXT NOT NULL,
	amount REAL NOT NULL,
	category TEXT
);


CREATE TABLE recurring (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	type TEXT NOT NULL,
	date TEXT NOT NULL,
	amount REAL NOT NULL,
	category TEXT
);
